# Site settings
title: Madhawa Karaunathilaka
description: Portfolio- Madhawa Karunathilka
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Madhawa Karunathilaka
user_description: I am a passionate, energetic Data Scientist. I keep up with existing technological advancements particularly in the field of data science and Machine Learning. I am willing to be challenged in any circumstances in order to gain knowledge and experience.
user_title: Data Scientist
email: modhawabk@gmail.com
twitter_username: madhawabk
github_username:  madhawabk
gplus_username:  madhawabk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
